### ISSUE TITLE
check all cases takeSurvey – register within survey, continue survey, finalize survey, within projectroom-page itself, within projectroom-info-page, etc

### ISSUE THREAD

**Issue by tassilomorino** [Senf-koeln/senf-monorepo#1278]

**Comment by lnvglr** [comment]
- [ ] register within survey
- [ ] continue survey
- [ ] finalize survey
- [ ] within projectroom-page itself
- [ ] within projectroom-info-page

**Comment by lnvglr** [comment]
[Uploading... image.png]

**Comment by lnvglr** [comment]
![image.png](https://images.zenhubusercontent.com/62d658a0d324e8912186792b/43709c68-c52c-4168-827c-b4b0c733ec28)
