### ISSUE TITLE
Chat with collaborators

### ISSUE THREAD

**Issue by cewevauha** [Senf-koeln/senf-monorepo#32]
As a member I want to be able to chat with collaborators in order to communicate about and progress with the action.

Important is, that this application is divided into Workspaces. It should not be one big workspace, but projectroom-related (at some point maybe also idea-related))

**Comment by tassilomorino** [comment]
![Group 342.png](https://images.zenhubusercontent.com/60f47913ad515f9e4c4346e5/6e365b57-cc7b-49b2-a4c5-3199e2cd16fe)

**Comment by tassilomorino** [comment]
https://www.youtube.com/watch?v=zQyrwxMPm88&t=188s&ab_channel=Fireship
