### ISSUE TITLE
weird bug with projectroomcard

### ISSUE THREAD

**Issue by tassilomorino** [Senf-koeln/senf-monorepo#466]
<img width="449" alt="Bildschirmfoto 2022-07-17 um 11 19 40" src="https://user-images.githubusercontent.com/49417005/179391996-531bb749-b345-4fdf-93ac-6e658e53a538.png">
<img width="474" alt="Bildschirmfoto 2022-07-17 um 11 18 53" src="https://user-images.githubusercontent.com/49417005/179392002-e86fa18e-09d3-4360-9398-addd9d0eb277.png">

**Comment by Digital-Coder** [comment]
@tassilomorino cant replicate
