### ISSUE TITLE
Theme: Return values with unit (if yes, which?) or without?

### ISSUE THREAD

**Issue by lnvglr** [Senf-koeln/senf-monorepo#714]
In the theme config, I think we should decide whether we return variables with a unit or without. My proposal is that we return units as numbers (without unit) and assume pixel values. This is kind of common practice in JS anyway.

We can then provide a px-to-rem function and devs can transform the values to rem as well.

What do you think @Digital-Coder, @simonorzel26, @tassilomorino?

**Comment by simonorzel26** [comment]
sounds good 👍
