### ISSUE TITLE
Verification problems

### ISSUE THREAD

**Issue by Digital-Coder** [Senf-koeln/senf-monorepo#852]
1. on testing page url will be different 
![image](https://user-images.githubusercontent.com/31192965/198056500-70fec545-c3b3-41ac-ac6a-115e81e54096.png)

2. /verify path opens authmodal, but it needs to check if email has been verified
using this functionality
![image](https://user-images.githubusercontent.com/31192965/198056974-c9fa4067-f019-48e4-8656-e999d26d5c7a.png)

**Comment by tassilomorino** [comment]
@Digital-Coder you can use env variables for the correct page urls, right? so for development, staging and production
