### ISSUE TITLE
Login is not possible with my web.de mail address -> also no failure message

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/senf-monorepo#911]

**Comment by lnvglr** [comment]
I cannot reproduce this bug. I have no web.de address and i failed to register one (...wtf haha). and with other non-gmail addresses i could register and login just fine

**Comment by Digital-Coder** [comment]
I suspect  it was because Christian registered on dev firebase env and tried to login in senf.app production build ( because verification link redirects there). 

But there could be something with email regex too where it validates as a wrong email and does not allow to login.
