### ISSUE TITLE
No failure message after login with a wrong password

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/senf-monorepo#912]

**Comment by lnvglr** [comment]
![image.png](https://images.zenhubusercontent.com/62d658a0d324e8912186792b/0ef636e3-d995-41d9-8538-b0b9804244ce)
this does show, do we want something nicer?

**Comment by Digital-Coder** [comment]
@lnvglr there is generateErrorMessage.js file, could be useful :)
