### ISSUE TITLE
After clicking on zur Anmeldung I get forwarded to Senf.Köln and login doesn't work

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/senf-monorepo#919]
![Bildschirmfoto 2022-11-03 um 12.07.43.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/f5a03722-dc3f-40bc-983b-8bccccb3948c)

**Comment by Digital-Coder** [comment]
Next time, we need to  change redirect url before testing
