### ISSUE TITLE
When refreshing page and trying to login with my mail, there is no button to login

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/senf-monorepo#924]
![Bildschirmfoto 2022-11-03 um 12.12.00.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/7695f913-053e-4085-a86c-59b3b0b73dc0)

**Comment by lnvglr** [comment]
https://github.com/Senf-koeln/senf-monorepo/commit/1dc8daa3e2648dbbbe5de7faacefd76547af5ed6

**Comment by Digital-Coder** [comment]
we still have a bug. When I use google chromes autocomplete and add a space at the end of a email
