### ISSUE TITLE
By Resetting my password, there is no confirmation screen that a new password/ mail is being sent out  Also mail which gets send out looks weird - Link not clickable - Your Senf.Koeln = Your Senf.app Team

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/senf-monorepo#925]
![Bildschirmfoto 2022-11-03 um 12.12.44.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/4a50f631-a57a-4c84-b872-0a7e590ad958)

**Comment by Digital-Coder** [comment]
fixed, but sent out email needs to be tested again with multiple  email providers.
