### ISSUE TITLE
Organization-Profile: Contact information is not visible (android phone)

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/senf-monorepo#959]
![Bildschirmfoto 2022-11-08 um 15.14.02.png](https://images.zenhubusercontent.com/62d82e8b6fa113ec2e67dc4a/dbf72150-1a23-46bb-bccc-6150083bc51f)

**Comment by tassilomorino** [comment]
@everyone, we have to take all style:{padding} out of the modal options, that breaks it! padding only to the children
