### ISSUE TITLE
There are some flaws by clicking on an initiative and then try to navigate to kalender, you end up somewhere else

### ISSUE THREAD

**Issue by christianwvh** [Senf-koeln/senf-monorepo#997]
https://images.zenhubusercontent.com/387246703/395540b4-a319-4b08-9efe-7c412239f08d/bildschirmaufnahme_2022_11_01_um_16_55_54___pascal_fuhr.mov

**Comment by christianwvh** [comment]
https://images.zenhubusercontent.com/387246703/a4032913-bf6e-4af0-bf24-0c7b7dbedb03/bildschirmaufnahme_2022_11_01_um_16_55_54___pascal_fuhr.mov

**Comment by Digital-Coder** [comment]
I cant replicate with existing organizations
